os: linux
jobs:
  include:
    - language: node_js
      node_js: node
      script:
        - ./gradlew buildClient
    - language: java
      jdk: openjdk15
      script:
        - ./gradlew buildServer
