spring:
  application:
    name: docusign-prototype-server
  jpa:
    hibernate:
      ddl-auto: create-drop
      database-platform: org.hibernate.dialiect.H2Dialect
  datasource:
    url: jdbc:h2:file:./h2/data;DATABASE_TO_UPPER=false
    username: sa
    password: ""
    driver-class: org.h2.Driver
    initialization-mode: always
  h2:
    console:
      enabled: true
