spring:
  application:
    name: docusign-prototype-server
  jpa:
    hibernate:
      ddl-auto: create-drop
      database-platform: org.hibernate.dialiect.H2Dialect
  datasource:
    url: jdbc:h2:file:./h2/data;DATABASE_TO_UPPER=false
    username: sa
    password: ""
    driver-class: org.h2.Driver
    initialization-mode: always
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          docusign:
            client-id: 5f178629-92f1-431f-a323-3b6852e823a0
            client-secret: 8f02b844-499f-460f-bda9-f354f5f2ce05
            authorization-grant-type: authorization_code
            redirectUri: "{baseUrl}/oauth2/authorization/docusign"
        provider:
          docusign:
            authorization-uri: https://account-d.docusign.com/oauth/auth
            token-uri: https://account-d.docusign.com/oauth/token
            user-info-uri: https://account-d.docusign.com/oauth/userinfo
